### PR TITLE
Adds agro range to ability caster

### PR DESCRIPTION
**Pull request by Drummerboy444**

### CODE REVIEW

**Comment by Drummerboy444** [comment]
[Add num_agroRange to oAbilityCaster](https://trello.com/c/GsLjRtXb/7-add-numagrorange-to-oabilitycaster)

**Comment by nick-wilson95** [comment]
May seem picky but I think agro should be aggro, should be doable with a find and replace.

**Comment by Drummerboy444** [comment]
Yeah good call, not too picky for me! Updated

**Comment by nick-wilson95** [comment]
Thanks - there are new conflicts as I merged your stats branch. Consider reviewing the BlueBeam ability branch first because that merges into master without any conflicts.

**Pull request merged**
